configured_endpoints: 106
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/nirvana-labs%2Fnirvana-35c794ea8c85de8e4ce3949f421374e75cfba5fff3b3dd506c0e72e4065b5342.yml
openapi_spec_hash: cb2900ce3cabe1fea13881cdf1ab5aae
config_hash: bb22b905ebcbbfc07f50e83327de150a
