#!/usr/bin/env bash

set -euo pipefail

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/nirvana-labs/nirvana-go,github.com/nirvana-labs/nirvana-go-staging"

go build -o terraform-provider-nirvana
