#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/nirvana-labs/nirvana-go,github.com/stainless-sdks/nirvana-go"

REPLACEMENT="${1:-"../Nirvana Labs-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/nirvana-labs/nirvana-go="$REPLACEMENT"
go mod tidy -e
